### get the request from server
GET http://localhost:8000
### get request
GET http://localhost:8000/api/v1/task

### get task fromserver
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{"task":"coding","hr":"15"}

### post task to server
DELETE   http://localhost:8000/api/v1/task