### get the request from server
GET http://localhost:8000
### get single or all  request
GET http://localhost:8000/api/v1/task/

### get task fromserver
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{"task":"coding","hr":"15","userId":"6278729feafc7e9be0d91870"}
### Updating the data
PATCH  http://localhost:8000/api/v1/task/
Content-Type: application/json

{
"_id":"626752580ea1c2d8b19467cf",
"hr":"4"
}

### post task to server
DELETE   http://localhost:8000/api/v1/task/626752aa0ea1c2d8b19467d7


### user api zone
###get user
GET  http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name":"Dipak",
    "email":"paudelsantosh508@gmail.com"
}
###create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name":"Dipaasdffkasd",
    "email":"paudasdfelsantosasdh508@gmail.com"
}
###delete user
DELETE http://localhost:8000/api/v1/user/627872a6eafc7e9be0d91872
